### PR TITLE
Kat unit testing

### PR DESCRIPTION
**Pull request by Katirene**
I should have all of the public functions behaviors mostly tested in the user-service-spec covered.  A couple questions.
-What is the best way to test the $window.location.href = '/#/home' line in the log out function?
-Also, I am unclear why in your test you have this line?  $httpBackend.when('GET', '/views/templates/home.html').respond({}).  Mocking the POST call and response makes sense but not this GET.
Thanks Ian.  Look over what I've done and I will move on to other services.
-Kat

### CODE REVIEW

**Comment by IanFelton** [comment]
Probably a relic from copying over from the other test. If you take it out and the test fails, then it's still needed.

Ian Felton

**Comment by Katirene** [comment]
Yes, It looks like it is a needed piece although its a bit puzzling.

**Comment by IanFelton** [comment]
So the templates are returned by http requests. Since the code runs in the browser, if an http request is made and the mock server isn't set up to handle it, it will fail. I deliberately placed it in the first test I wrote, but never tested if it was needed in the latest test. So that is why it's there, the only uncertainty for me, was if that particular test needed it. 

Ian Felton

**Comment by Katirene** [comment]
I see. That's the part I was missing. I didn't catch that the template swaps would also need to be a http mock. Makes sense.

**Pull request closed without merging**
